### PR TITLE
Add PCG internal module

### PR DESCRIPTION
**Pull request by cchalmers**
Here's my PCG code as promised (#1) . I've also included the bounded random number code I've used in `pcg-random`.

The only thing I'm not sure about is my `split`. It passed big-crunch and die-harder but there's probably a better way to do it. Maybe we should ask the pcg author?

### CODE REVIEW

**Comment by cartazio** [comment]
Great!  
If I don't get to code review in the day two days, please poke me via email or irc to get through it. 

I've done a first pass read through and it looks good.  But need to digest and compare with a few other things.

**Comment by cartazio** [comment]
One possibly silly question: why is there two exposed modules lines?

**Comment by cchalmers** [comment]
Ha, I just copied the line without thinking. Fixed it now, also took out the rest of the cabal comments.

**Comment by cartazio** [comment]
I generally like leaving the other comments in, but I won't object too
strongly to the removal ... even though my own habits are to always leave
them in the cabal file.

Could you maybe revert that part? 😇😊

**Comment by cchalmers** [comment]
Sure, I've revered it.

**Comment by cchalmers** [comment]
@cartazio Hey, this is me reminding you to look at this.

**Comment by cartazio** [comment]
Woot. Thanks.  I'll poke at it this week

**Comment by cartazio** [comment]
@cchalmers i may or may not take an axe to the code to to clean up some style preferences
(eg i prefer do notation for non recursive "imperative" code), but looks lovely and many thanks! :)

**Pull request merged**
